
import React, { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Leaf, TreePine, Recycle, DropletIcon, BookOpen } from 'lucide-react';
import { cn } from '@/lib/utils';
import { AspectRatio } from '@/components/ui/aspect-ratio';
import { ArticleView } from './ArticleView';

const articles = {
  climate: [
    {
      id: 'everyday-choices',
      title: "The Surprising Impact of Everyday Choices",
      excerpt: "Small daily decisions can add up to significant environmental benefits over time.",
      category: "Climate",
      imageSrc: "https://images.unsplash.com/photo-1536599424071-0b215a388ba7?auto=format&fit=crop&q=80&w=400",
      readTime: "4 min read",
      author: "Maria Santos",
      date: "June 12, 2023",
      content: [
        "Every day, we make choices that can either contribute to or reduce our environmental footprint. From the moment we wake up to when we go to bed, these seemingly small decisions accumulate to create a significant impact on our planet.",
        "One of the most impactful choices we make daily involves transportation. Choosing to walk, bike, or use public transportation instead of driving alone can reduce your carbon footprint by up to 30%. Even carpooling twice a week can save about 1,600 pounds of greenhouse gas emissions annually.",
        "Our food choices also matter tremendously. Reducing meat consumption by just one meal per week can save the equivalent of driving 348 miles in terms of greenhouse gas emissions. Eating locally-produced, seasonal foods further reduces the carbon footprint associated with long-distance food transportation.",
        "At home, simple actions like adjusting your thermostat by just 1-2 degrees can reduce your energy consumption by up to 10%. Similarly, washing clothes in cold water instead of hot can save up to 500 pounds of carbon dioxide emissions annually for a typical household.",
        "Electronic devices are another area where small changes make a difference. Unplugging chargers and devices when not in use prevents 'phantom energy' consumption, which can account for up to 10% of a home's electricity use.",
        "Water usage is often overlooked, but turning off the tap while brushing teeth can save up to 8 gallons of water per day. Installing low-flow fixtures can reduce water consumption by 30-50% without sacrificing performance.",
        "By being mindful of these everyday choices, we can collectively create a substantial positive impact on our environment. Remember that sustainability isn't about perfection—it's about making better choices when and where we can."
      ]
    },
    {
      id: 'carbon-footprints',
      title: "Understanding Carbon Footprints",
      excerpt: "A comprehensive guide to understanding and reducing your carbon footprint.",
      category: "Climate",
      imageSrc: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=400",
      readTime: "8 min read",
      author: "Dr. James Wilson",
      date: "August 3, 2023",
      content: [
        "A carbon footprint represents the total amount of greenhouse gases generated by our actions. Understanding your personal carbon footprint is the first step toward making meaningful reductions in your environmental impact.",
        "The average Filipino generates approximately 1.9 metric tons of CO2 per year, significantly lower than the global average of 4.7 metric tons. However, as the Philippines continues to develop economically, this number is expected to rise unless sustainable practices are widely adopted.",
        "Transportation contributes significantly to personal carbon footprints. In urban areas like Metro Manila, traffic congestion leads to increased emissions. Opting for public transportation, carpooling, or using the growing network of bike lanes can substantially reduce this impact.",
        "Home energy use is another major contributor. The tropical climate of the Philippines means that cooling systems often consume significant electricity. Using energy-efficient appliances, proper insulation, and ceiling fans instead of air conditioning when possible can make a substantial difference.",
        "Food choices play a crucial role in your carbon footprint. The typical Filipino diet, which includes rice as a staple, has a lower carbon footprint than Western diets heavy in beef. However, the increasing consumption of processed foods and meat is changing this pattern.",
        "Waste management also matters. The Philippines faces significant challenges with waste disposal, with many areas lacking proper recycling infrastructure. Practicing waste segregation, composting organic waste, and avoiding single-use plastics can help reduce methane emissions from landfills.",
        "By making thoughtful choices in these key areas, Filipinos can maintain a relatively low carbon footprint while enjoying improved quality of life. Remember that collective action, when millions of people make small changes, creates significant positive environmental impact."
      ]
    }
  ],
  water: [
    {
      id: 'water-conservation',
      title: "Water Conservation at Home: Easy Steps",
      excerpt: "Simple ways to reduce your water footprint without disrupting your daily routine.",
      category: "Water",
      imageSrc: "https://images.unsplash.com/photo-1527066236128-2ff79f7b9705?auto=format&fit=crop&q=80&w=400",
      readTime: "5 min read",
      author: "Elena Rivera",
      date: "July 15, 2023",
      content: [
        "Water is one of our most precious resources, yet we often take it for granted. In the Philippines, despite being surrounded by water, many regions face water scarcity issues, especially during dry seasons. Implementing simple water conservation practices at home can make a significant difference.",
        "In the bathroom, where approximately 60% of indoor water is used, small changes can yield significant savings. Installing low-flow showerheads can reduce water usage by up to 40% while maintaining adequate pressure. A five-minute shower instead of a bath can save up to 100 liters of water.",
        "Toilet flushing accounts for about 30% of household water use. Consider installing dual-flush toilets or placing a water displacement device in your tank. Checking for and fixing leaks promptly is crucial—a leaking toilet can waste up to 200 liters per day.",
        "In the kitchen, washing dishes efficiently can save substantial amounts of water. If washing by hand, don't let the water run continuously. If using a dishwasher, run it only when full. Keeping a pitcher of drinking water in the refrigerator eliminates the need to run the tap until it's cold.",
        "Laundry is another area where conservation is possible. Modern washing machines use less water than older models, but regardless of your machine's age, washing full loads rather than partial loads maximizes efficiency. Consider reusing towels several times before washing and wearing clothes like jeans multiple times.",
        "Outside the home, water-efficient landscaping (xeriscaping) can reduce outdoor water use by 50-75%. Collecting rainwater in barrels for watering plants is especially effective during the rainy season in the Philippines, providing a free source of water for gardens.",
        "By implementing these simple measures, a typical Filipino household can reduce water consumption by 30-40%. This not only conserves a valuable resource but also reduces utility bills and the energy used to heat and pump water."
      ]
    }
  ],
  waste: [
    {
      id: 'zero-waste',
      title: "Zero Waste Lifestyle: Getting Started",
      excerpt: "Practical tips for beginners looking to reduce their household waste.",
      category: "Waste",
      imageSrc: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=400",
      readTime: "7 min read",
      author: "Marco Santos",
      date: "May 8, 2023",
      content: [
        "The zero waste movement has gained momentum in the Philippines as more people recognize the urgent need to address the country's waste management challenges. Starting a zero waste journey doesn't mean eliminating all waste overnight—it's about making progressive steps toward reducing what we send to landfills.",
        "Begin by conducting a waste audit in your home. For one week, observe what you throw away. This awareness helps identify your largest sources of waste and areas where you can make the most impactful changes. Common sources include food packaging, single-use plastics, and food waste.",
        "The kitchen is often the best place to start your zero waste journey. Invest in reusable containers, beeswax wraps instead of plastic wrap, and cloth produce bags for grocery shopping. At Filipino markets, it's becoming increasingly common to bring your own containers for fresh produce, meat, and seafood.",
        "Shopping in bulk is another effective strategy. Stores like The Humble Market in Manila and Ritual in Makati allow customers to bring their own containers for rice, grains, spices, and cleaning products. This eliminates packaging waste while often saving money.",
        "In the bathroom, solid bar soaps, shampoos, and toothpaste tablets can replace products in plastic packaging. Menstrual cups or period panties offer sustainable alternatives to disposable products. Bamboo toothbrushes, abundant in the Philippines, replace plastic ones.",
        "Food waste, which accounts for a significant portion of household waste, can be addressed through meal planning, proper food storage, and composting. Urban composting systems are particularly suitable for Filipino apartments and can reduce organic waste while creating nutrient-rich soil for plants.",
        "Remember that zero waste is a journey, not a destination. In the Philippine context, where sustainable options are still developing, focus on progress rather than perfection. Each small change contributes to the collective effort to preserve our beautiful islands for future generations."
      ]
    }
  ],
  energy: [
    {
      id: 'renewable-energy',
      title: "Renewable Energy: The Future is Now",
      excerpt: "How renewable energy is transforming our world and how you can be part of it.",
      category: "Energy",
      imageSrc: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&q=80&w=400",
      readTime: "6 min read",
      author: "Dr. Antonio Reyes",
      date: "September 5, 2023",
      content: [
        "Renewable energy has moved from an alternative option to a mainstream solution in the global fight against climate change. In the Philippines, a country blessed with abundant renewable resources, the transition to clean energy presents both environmental benefits and economic opportunities.",
        "Solar power has seen remarkable growth in the Philippines, with installations ranging from large solar farms to residential rooftop systems. The country receives an average of 5.1 kWh/m² of solar radiation daily, making it ideal for solar energy generation. For homeowners, the initial investment in solar panels typically pays for itself within 5-7 years through reduced electricity bills.",
        "Wind energy is another promising resource, particularly in northern Luzon and coastal areas. The Bangui Wind Farm in Ilocos Norte was the first commercial wind farm in Southeast Asia and continues to be a model for sustainable energy development. Community-owned wind projects are emerging as a way to democratize energy production.",
        "Geothermal energy has long been a strength for the Philippines, which ranks as the world's third-largest producer. The stable, 24/7 generation capability of geothermal plants makes them an excellent baseload power source, complementing the intermittent nature of solar and wind.",
        "Hydropower and ocean energy also hold significant potential. Small-scale, run-of-river hydro projects offer electricity generation with minimal environmental impact, while emerging technologies to harness energy from waves and tides could take advantage of the Philippines' 36,289 kilometers of coastline.",
        "For individual Filipinos, participating in the renewable energy transition can take many forms. Beyond installing solar panels, options include joining community renewable energy cooperatives, choosing electricity providers that offer green energy options, and advocating for supportive government policies.",
        "The shift to renewable energy in the Philippines isn't just environmentally necessary—it's economically advantageous. By reducing dependence on imported fossil fuels, expanding energy access to remote communities, and creating jobs in the green economy, renewable energy represents a path to a more sustainable and prosperous future for all Filipinos."
      ]
    }
  ]
};

interface ArticleCardProps {
  title: string;
  excerpt: string;
  category: string;
  imageSrc: string;
  readTime: string;
  onClick: () => void;
  className?: string;
}

function ArticleCard({
  title,
  excerpt,
  category,
  imageSrc,
  readTime,
  onClick,
  className,
}: ArticleCardProps) {
  return (
    <Card 
      className={cn('glass-card overflow-hidden hover-card cursor-pointer', className)}
      onClick={onClick}
    >
      <div className="relative">
        <AspectRatio ratio={16 / 9}>
          <img
            src={imageSrc}
            alt={title}
            className="w-full h-full object-cover"
            loading="lazy"
          />
        </AspectRatio>
        <div className="absolute top-3 left-3">
          <div className="bg-background/80 backdrop-blur-sm px-2 py-1 rounded-md">
            <span className="text-xs font-medium">{category}</span>
          </div>
        </div>
      </div>
      <CardContent className="p-4 space-y-2">
        <h3 className="font-medium line-clamp-2">{title}</h3>
        <p className="text-sm text-muted-foreground line-clamp-2">{excerpt}</p>
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            <BookOpen className="h-3 w-3 mr-1 text-muted-foreground" />
            <span className="text-xs text-muted-foreground">{readTime}</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export function Education() {
  const [selectedArticle, setSelectedArticle] = useState<any>(null);
  const [activeTab, setActiveTab] = useState('all');
  
  // Function to get all articles
  const getAllArticles = () => {
    return [
      ...articles.climate,
      ...articles.water,
      ...articles.waste,
      ...articles.energy
    ];
  };
  
  // Get articles based on active tab
  const getArticlesForTab = () => {
    switch (activeTab) {
      case 'climate':
        return articles.climate;
      case 'water':
        return articles.water;
      case 'waste':
        return articles.waste;
      case 'energy':
        return articles.energy;
      case 'all':
      default:
        return getAllArticles();
    }
  };
  
  const handleTabChange = (value: string) => {
    setActiveTab(value);
    setSelectedArticle(null);
  };
  
  const handleArticleClick = (article: any) => {
    setSelectedArticle(article);
    window.scrollTo(0, 0);
  };
  
  const handleBackClick = () => {
    setSelectedArticle(null);
  };

  if (selectedArticle) {
    return <ArticleView article={selectedArticle} onBack={handleBackClick} />;
  }

  return (
    <section className="space-y-6 animate-fade-in">
      <div className="space-y-2">
        <h1 className="text-3xl font-medium tracking-tight">Learn</h1>
        <p className="text-muted-foreground">Discover sustainability knowledge</p>
      </div>
      
      <Tabs value={activeTab} onValueChange={handleTabChange} className="w-full">
        <TabsList className="w-full grid grid-cols-5 h-auto p-1 bg-muted rounded-lg">
          <TabsTrigger value="all" className="py-2 text-xs">All</TabsTrigger>
          <TabsTrigger value="climate" className="py-2 text-xs">Climate</TabsTrigger>
          <TabsTrigger value="water" className="py-2 text-xs">Water</TabsTrigger>
          <TabsTrigger value="waste" className="py-2 text-xs">Smart Waste</TabsTrigger>
          <TabsTrigger value="energy" className="py-2 text-xs">Energy</TabsTrigger>
        </TabsList>
        
        <TabsContent value={activeTab} className="mt-6 space-y-4">
          {getArticlesForTab().map((article) => (
            <ArticleCard
              key={article.id}
              title={article.title}
              excerpt={article.excerpt}
              category={article.category}
              imageSrc={article.imageSrc}
              readTime={article.readTime}
              onClick={() => handleArticleClick(article)}
            />
          ))}
        </TabsContent>
      </Tabs>
    </section>
  );
}
